// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicLayout: typeof import('./layouts/BasicLayout.vue')['default']
    DarkColorTest: typeof import('./components/DarkColorTest.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Header: typeof import('./layouts/components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Iframe: typeof import('./layouts/Iframe.vue')['default']
    LightColorTest: typeof import('./components/LightColorTest.vue')['default']
    Menu: typeof import('./layouts/components/menu/Menu.vue')['default']
    MenuItem: typeof import('./layouts/components/menu/MenuItem.vue')['default']
    PageLayout: typeof import('./layouts/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./layouts/components/Sidebar.vue')['default']
    SubMenuItem: typeof import('./layouts/components/menu/SubMenuItem.vue')['default']
    ThemePicker: typeof import('./components/ThemePicker.vue')['default']
  }

}
